In [5]:
import numpy as np

In [14]:
arr = np.zeros((4, 2), dtype=np.uint8)
arr[:] = 1, 2
arr

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0]], dtype=uint8)

In [16]:
arr[:] = 1, 2

arr

array([[1, 2],
       [1, 2],
       [1, 2],
       [1, 2]], dtype=uint8)

In [9]:
arr = np.array([1, 2, 3])

arr

array([1, 2, 3])

In [11]:
arr[:] = 0, 255, 8

arr

array([  0, 255,   8])

In [22]:
nums = np.zeros((4, 2, 3), dtype=np.uint8)

nums

array([[[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]]], dtype=uint8)

In [24]:
nums[:] = 0, 255, 0

nums

array([[[  0, 255,   0],
        [  0, 255,   0]],

       [[  0, 255,   0],
        [  0, 255,   0]],

       [[  0, 255,   0],
        [  0, 255,   0]],

       [[  0, 255,   0],
        [  0, 255,   0]]], dtype=uint8)